const ActionTypes = {
  FETCH_NEWS_START: 'FETCH_NEWS_START',
  FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
  FETCH_NEWS_ERROR: 'FETCH_NEWS_ERROR',
  START_DATE_SELECTED: 'START_DATE_SELECTED',
  END_DATE_SELECTED: 'END_DATE_SELECTED',
  FETCH_PLOT_DATA_START: 'FETCH_PLOT_DATA_START',
  FETCH_PLOT_DATA_SUCCESS: 'FETCH_PLOT_DATA_SUCCESS',
  FETCH_PLOT_DATA_ERROR: 'FETCH_PLOT_DATA_ERROR'
};

export default ActionTypes;
